import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NextAuthProvider from "@/components/NextAuthProvider"; // Import Provider
import { Toaster } from "@/components/ui/sonner";
const inter = Inter({ subsets: ["latin"] });
import "nprogress/nprogress.css";
import { Chatbot } from "@/components/chatbot";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          {children}
          <Toaster />
          <Chatbot />
        </NextAuthProvider>
      </body>
    </html>
  );
}
